services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        USERNAME: ${USERNAME:-developer}
        GROUPNAME: ${GROUPNAME:-developer}
    container_name: stellar-js
    environment:
      - NODE_ENV=development
      - DATABASE_PATH=/home/developer/works/data/stellar.db
      - LOG_LEVEL=debug
    env_file:
      - .env
    volumes:
      # Data persistence (SQLite database)
      - stellar_data:/home/developer/works/data
      # Mount source code for development
      - .:/home/developer/works:cached
      - node_modules_data:/home/developer/works/node_modules
    working_dir: /home/developer/works
    command: tail -f /dev/null
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - stellar-network

volumes:
  stellar_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./docker-volumes/data
  node_modules_data:
    driver: local

networks:
  stellar-network:
    driver: bridge
